// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSample(arg1, arg2) {
  return window['go']['main']['App']['AddSample'](arg1, arg2);
}

export function AddWord(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddWord'](arg1, arg2, arg3);
}

export function ChangeWordCount(arg1) {
  return window['go']['main']['App']['ChangeWordCount'](arg1);
}

export function Debugging(arg1) {
  return window['go']['main']['App']['Debugging'](arg1);
}

export function ForgetPassword(arg1, arg2) {
  return window['go']['main']['App']['ForgetPassword'](arg1, arg2);
}

export function GetLearnedWords(arg1) {
  return window['go']['main']['App']['GetLearnedWords'](arg1);
}

export function GetProgression(arg1) {
  return window['go']['main']['App']['GetProgression'](arg1);
}

export function GetRandomWords() {
  return window['go']['main']['App']['GetRandomWords']();
}

export function GetUserID(arg1) {
  return window['go']['main']['App']['GetUserID'](arg1);
}

export function GetWords(arg1) {
  return window['go']['main']['App']['GetWords'](arg1);
}

export function UpdateWordStates(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWordStates'](arg1, arg2, arg3);
}

export function UserLogin(arg1, arg2) {
  return window['go']['main']['App']['UserLogin'](arg1, arg2);
}

export function UserRegister(arg1, arg2) {
  return window['go']['main']['App']['UserRegister'](arg1, arg2);
}
