// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {types} from '../models';

export function AddSample(arg1:string,arg2:string):Promise<void>;

export function AddWord(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ChangeWordCount(arg1:number):Promise<void>;

export function Debugging(arg1:any):Promise<void>;

export function ForgetPassword(arg1:string,arg2:string):Promise<void>;

export function GetLearnedWords(arg1:number):Promise<Array<string>>;

export function GetProgression(arg1:number):Promise<main.Progression>;

export function GetRandomWords():Promise<Array<string>>;

export function GetUserID(arg1:string):Promise<number>;

export function GetWords(arg1:number):Promise<Array<types.Word>>;

export function UpdateWordStates(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function UserLogin(arg1:string,arg2:string):Promise<boolean>;

export function UserRegister(arg1:string,arg2:string):Promise<void>;
